### ISSUE TITLE
store: `imageTransformOptions` need validation on `w` width property

### ISSUE THREAD

**Issue by tjonger** [compasjs/compas#1428]
Error from sharp (below) because `w` in (`T.reference("store", "imageTransformOptions"`) is allowed to be zero. But sharp needs a minimum of `1`.

```shell
{
    "name": "Error",
    "message": "Expected positive integer for width but received 0 of type number",
    "stack": [
      "at Object.invalidParameterError (/app/node_modules/sharp/lib/is.js:124:10)",
      "at Sharp.resize (/app/node_modules/sharp/lib/resize.js:214:16)",
      "at sendTransformedImage (file:///app/node_modules/@compas/store/src/send-transformed-image.js:103:23)",
      "at async categoryHandlers.image (file:///app/src/category/controller.js:101:3)",
      "at async file:///app/node_modules/@compas/server/src/middleware/notFound.js:8:5",
      "at async file:///app/node_modules/@compas/server/src/middleware/error.js:33:7",
      "at async file:///app/node_modules/@compas/server/src/middleware/log.js:80:5"
    ]
}
```

**Comment by dirkdev98** [comment]
Dang, good catch!
