### ISSUE TITLE
create-compas: error formatting and unzip error

### ISSUE THREAD

**Issue by Mitchell-Ryan** [compasjs/compas#2032]
While using any of the new `npx create-compas` commands, the code breaks while unzipping. Also, error formatting is missing.

Example:
```
❯ npx create-compas@latest --template with-auth

{"level":"info","time":1662028440097,"context":{"type":"create-compas"},"message":"Experimental!"}
{"level":"info","time":1662028440097,"context":{"type":"create-compas"},"message":"Resolved template url: '[https://github.com/compasjs/compas/tree/v0.0.213/./examples/with-auth](https://github.com/compasjs/compas/tree/v0.0.213/examples/with-auth)'"}
{"level":"info","time":1662028440097,"context":{"type":"create-compas"},"message":"Output directory: '/Users/mitchell/projects/compas-with-auth'"}
{"level":"info","time":1662028440098,"context":{"type":"create-compas"},"message":"Resolving remote template..."}
{"level":"info","time":1662028440353,"context":{"type":"create-compas"},"message":"Downloading and extracting template..."}
{"level":"error","time":1662028440709,"context":{"type":"create-compas"},"message":{"type":"error","message":"Error caught from callback passed in `mainFn`","error":{"name":"Error","message":"Premature close","stack":["at new NodeError (node:internal/errors:393:5)","at Unpack.<anonymous> (node:internal/streams/pipeline:352:14)","at Unpack.emit (node:events:525:35)","at [maybeClose] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/unpack.js:228:12)","at Unpack.opt.ondone (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/unpack.js:129:23)","at Unpack.emit (node:events:525:35)","at [emit] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:285:12)","at [maybeEnd] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:401:17)","at [consumeChunk] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:432:21)","at Unzip.<anonymous> (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:351:29)"]}}}
```

**Comment by dirkdev98** [comment]
Thanks for reporting! 
#2037  forces the logger use to use the pretty printer and also adds a check if the template that is used really exists. 

The docs already mention `with-auth` but it is not yet created, sorry for the confusion. We use #1987 to track template creation.
