### ISSUE TITLE
examples(with-auth): unzip error on create with auth

### ISSUE THREAD

**Issue by Mitchell-Ryan** [compasjs/compas#2105]
Error found in https://github.com/compasjs/compas/issues/2049

While using `npx create-compas@latest --template with-auth`

```
14:55:46.235 error[create-compas] {
  type: 'error',
  message: 'Error caught from callback passed in `mainFn`',
  error: {
    name: 'Error',
    message: 'Premature close',
    stack: [
      'at new NodeError (node:internal/errors:393:5)',
      'at Unpack.<anonymous> (node:internal/streams/pipeline:352:14)',
      'at Unpack.emit (node:events:525:35)',
      'at [maybeClose] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/unpack.js:228:12)',
      'at Unpack.opt.ondone (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/unpack.js:129:23)',
      'at Unpack.emit (node:events:525:35)',
      'at [emit] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:285:12)',
      'at [maybeEnd] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:401:17)',
      'at [consumeChunk] (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:432:21)',
      'at Unzip.<anonymous> (/Users/mitchell/.npm/_npx/9860e88e3e1de73f/node_modules/tar/lib/parse.js:351:29)'
    ]
  }
}
```

**Comment by dirkdev98** [comment]
Thanks for creating the issue. Seems to be related to npm/node-tar#321
