### ISSUE TITLE
code-gen: relations to tables with non uuid primary key breaks

### ISSUE THREAD

**Issue by tjonger** [compasjs/compas#811]
Discussed IRL, but reference and summary below. 

Te reproduce:
```node
const job = T.reference("store", "job");

// entity 
T.object("entity")
  .shortName("hi")
  .keys({
    foo: T.string(),
  })
  .enableQueries({ withDates: true })
  .relations(
    T.manyToOne("jobId", job, "entityRef"),
  );

// add "back" relation to existing compas store entity
app.addRelations(
  job,
  T.oneToMany("entityRef", table("entity")),
);
```

Exception:
```shell
09:38:44.994 error[generate] {
  type: 'error',
  message: 'Error caught from callback passed in `mainFn`',
  error: {
    name: 'TypeError',
    message: "Cannot read property 'floatingPoint' of undefined",
    stack: [
      'at number (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/generator/sql/structure.js:20:24)',
      'at internalQueryBuilderForType (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/generator/sql/query-builder.js:436:21)',
      'at queryBuilderForType (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/generator/sql/query-builder.js:194:9)',
      'at generateQueryBuilder (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/generator/sql/query-builder.js:25:12)',
      'at generateModelFiles (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/generator/sql/models.js:23:5)',
      'at generate (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/generator/index.js:138:5)',
      'at App.generate (file:///Users/danielhansen/**/**/node_modules/@compas/code-gen/src/App.js:305:26)',
      'at main (file:///Users/danielhansen/**/**/scripts/generate.js:23:13)'
    ]
  }
}
```

**Comment by dirkdev98** [comment]
Thanks, reproduced!
